import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@component/styles/Home.module.css'
import Header from '@component/components/header'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Home - Techbarn</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
          <Header />
        <section>
          {/* Banner */}
        </section>
        <section>
          {/* column-1 */}
            {/* posts */}
            {/* posts */}
            {/* posts */}
            {/* posts */}
          {/* column-1 */}

          {/* column-2 */}
            {/* tags */}
            {/* featured posts */}
            {/* footer */}
          {/* column-2 */}
        </section>
      </main>
    </>
  )
}
